# Generated by Django 2.1.5 on 2019-10-09 02:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('creator', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContentInvestigator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Content')),
                ('inv', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creator.Investigator')),
            ],
        ),
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Content')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creator.Item')),
            ],
        ),
        migrations.CreateModel(
            name='ContentMania',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Content')),
                ('mania', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creator.Mania')),
            ],
        ),
        migrations.CreateModel(
            name='ContentOccupation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Content')),
                ('occ', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creator.Occupation')),
            ],
        ),
        migrations.CreateModel(
            name='ContentPhobia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Content')),
                ('phobia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creator.Phobia')),
            ],
        ),
        migrations.CreateModel(
            name='ContentSpell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Content')),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creator.Spell')),
            ],
        ),
        migrations.CreateModel(
            name='ContentTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Content')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creator.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='ContentUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Content')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContentWeapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Content')),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creator.Weapon')),
            ],
        ),
    ]
