# Generated by Django 2.1.5 on 2019-09-22 23:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0003_auto_20190922_2343'),
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contenttag',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Content'),
        ),
        migrations.AddField(
            model_name='contenttag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creator.Tag'),
        ),
    ]
