# Generated by Django 2.1.5 on 2019-01-23 02:17

import creator.models
from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investigator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('player', models.CharField(max_length=50)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('residence', models.CharField(max_length=80)),
                ('birthplace', models.CharField(max_length=80)),
                ('age', models.PositiveIntegerField(default=18)),
            ],
        ),
        migrations.CreateModel(
            name='InvestigatorAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('attr', django_enumfield.db.fields.EnumField(default=1, enum=creator.models.Attribute)),
                ('value', models.PositiveIntegerField()),
                ('investigator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creator.Investigator')),
            ],
        ),
        migrations.CreateModel(
            name='InvestigatorSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('value', models.PositiveIntegerField(default=0)),
                ('investigator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creator.Investigator')),
            ],
        ),
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=50)),
                ('credit_rating_min', models.PositiveIntegerField()),
                ('credit_rating_max', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OccupationAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('attr', django_enumfield.db.fields.EnumField(default=1, enum=creator.models.Attribute)),
                ('modifier', models.PositiveIntegerField()),
                ('optional', models.BooleanField(default=False)),
                ('occupation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creator.Occupation')),
            ],
        ),
        migrations.CreateModel(
            name='OccupationSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('occupation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creator.Occupation')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='occupationskills',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creator.Skills'),
        ),
        migrations.AddField(
            model_name='investigatorskills',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creator.Skills'),
        ),
        migrations.AddField(
            model_name='investigator',
            name='occupation',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='creator.Occupation'),
        ),
    ]
