# Generated by Django 2.1.4 on 2019-01-02 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investigator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('player', models.CharField(max_length=50)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('residence', models.CharField(max_length=80)),
                ('birthplace', models.CharField(max_length=80)),
                ('age', models.PositiveIntegerField(default=18)),
                ('strength', models.IntegerField()),
                ('dexterity', models.IntegerField()),
                ('power', models.IntegerField()),
                ('constitution', models.IntegerField()),
                ('appearence', models.IntegerField()),
                ('education', models.IntegerField()),
                ('size', models.IntegerField()),
                ('intelligence', models.IntegerField()),
            ],
        ),
    ]
