# Generated by Django 2.1.4 on 2019-01-04 03:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(choices=[('Strength', 'STR'), ('Dexterity', 'DEX'), ('Appearence', 'APP'), ('Educated', 'EDU'), ('Intelligence', 'INT'), ('Size', 'SIZ'), ('Constitution', 'CON'), ('Luck', 'LCK'), ('Power', 'PWR')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='InvestigatorAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('value', models.PositiveIntegerField()),
                ('attr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creator.Attribute')),
            ],
        ),
        migrations.CreateModel(
            name='InvestigatorSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=50)),
                ('credit_rating_min', models.PositiveIntegerField()),
                ('credit_rating_max', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OccupationAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('modifier', models.PositiveIntegerField()),
                ('optional', models.BooleanField(default=False)),
                ('attr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creator.Attribute')),
                ('occupation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creator.Occupation')),
            ],
        ),
        migrations.CreateModel(
            name='OccupationSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('occupation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creator.Occupation')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=50)),
                ('value', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='investigator',
            name='appearence',
        ),
        migrations.RemoveField(
            model_name='investigator',
            name='constitution',
        ),
        migrations.RemoveField(
            model_name='investigator',
            name='dexterity',
        ),
        migrations.RemoveField(
            model_name='investigator',
            name='education',
        ),
        migrations.RemoveField(
            model_name='investigator',
            name='intelligence',
        ),
        migrations.RemoveField(
            model_name='investigator',
            name='power',
        ),
        migrations.RemoveField(
            model_name='investigator',
            name='size',
        ),
        migrations.RemoveField(
            model_name='investigator',
            name='strength',
        ),
        migrations.AddField(
            model_name='investigator',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='occupationskills',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creator.Skills'),
        ),
        migrations.AddField(
            model_name='investigatorskills',
            name='investigator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creator.Investigator'),
        ),
        migrations.AddField(
            model_name='investigatorskills',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creator.Skills'),
        ),
        migrations.AddField(
            model_name='investigatorattribute',
            name='investigator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creator.Investigator'),
        ),
        migrations.AddField(
            model_name='investigator',
            name='occupation',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='creator.Occupation'),
        ),
    ]
